# Generated by Django 5.2.7 on 2025-10-07 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('report_url', models.URLField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
