# Generated by Django 5.2.7 on 2025-10-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='users.patient'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='users.professional'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('professional', 'patient', 'week_start')},
        ),
    ]
