# Generated by Django 5.2.7 on 2025-10-07 13:25

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sin título', max_length=100)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('selected_emotions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('fear', 'Fear'), ('anger', 'Anger'), ('disgust', 'Disgust'), ('surprise', 'Surprise')], max_length=20), size=None)),
                ('emotion_summary', models.JSONField()),
                ('content_length', models.IntegerField(editable=False)),
            ],
        ),
    ]
