# Generated by Django 5.2.7 on 2025-10-16 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='selected_emotions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('alegria', 'Alegría'), ('tristeza', 'Tristeza'), ('ira', 'Ira'), ('miedo', 'Miedo'), ('asco', 'Asco'), ('sorpresa', 'Sorpresa')], max_length=20), size=None),
        ),
    ]
