# Generated by Django 5.2.7 on 2025-10-17 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diaryentry_selected_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_emotions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='emotion_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='selected_emotions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('alegria', 'Alegría'), ('tristeza', 'Tristeza'), ('ira', 'Ira'), ('miedo', 'Miedo'), ('asco', 'Asco'), ('sorpresa', 'Sorpresa')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
