# Generated by Django 5.2.7 on 2025-10-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diaryentry_analyzed_emotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='emotion_summary',
        ),
    ]
