# Generated by Django 5.2.7 on 2025-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_diaryentry_emotion_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='analyzed_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
