# Generated by Django 5.2.7 on 2025-11-06 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diaryentry_analyzed_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
