# Generated by Django 5.2.7 on 2025-10-07 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='link_code_changes_today',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='link_code_last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
