# Generated by Django 5.2.7 on 2025-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_professional_link_code_changes_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('non_binary', 'No binario'), ('other', 'Otro')], max_length=16),
        ),
    ]
