# Generated by Django 5.2.7 on 2025-10-10 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=10)),
                ('verification_code_expires_at', models.DateTimeField()),
                ('user_data', models.JSONField()),
                ('profile_data', models.JSONField()),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_preregistration',
                'indexes': [models.Index(fields=['email'], name='auth_prereg_email_7e6237_idx'), models.Index(fields=['verification_code'], name='auth_prereg_verific_9a1e1c_idx')],
            },
        ),
    ]
