# Generated by Django 5.2.7 on 2025-10-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_preregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado de Revisión'),
        ),
    ]
