# Generated by Django 5.2.7 on 2025-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_professional_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailchangerequest',
            name='token',
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='hashed_verification_code',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
