# Generated by Django 5.2.7 on 2025-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_emailchangerequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
