# Generated by Django 5.2.7 on 2025-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_patient_first_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
