# Generated by Django 5.2.7 on 2025-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_patient_current_streak_patient_last_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maternal_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
