# Generated by Django 5.2.7 on 2025-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_maternal_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('professional', 'Professional')], max_length=20),
        ),
    ]
